const actionTypes = {
  ANIMATION: 'ANIMATION',
  INIT_TIME_SYNC: 'INIT_TIME_SYNC',
  POSITION: 'POSITION',
  SERVER_TIME: 'SERVER_TIME',
  START_ANIMATION: 'START_ANIMATION',
  STOP_ANIMATION: 'STOP_ANIMATION',
};

module.exports = actionTypes;
