module.exports = {
  ANIMATION: 'ANIMATION',
  INIT_TIME_SYNC: 'INIT_TIME_SYNC',
  POSITION: 'POSITION',
  SERVER_TIME: 'SERVER_TIME',
  SET_ANIMATION: 'SET_ANIMATION',
  START_ANIMATION: 'START_ANIMATION',
  STOP_ANIMATION: 'STOP_ANIMATION',
  CONNECTION_ADDED: 'connections/CONNECTION_ADDED',
  CONNECTION_REMOVED: 'connections/CONNECTION_REMOVED',
  CURRENT_CONNECTIONS: 'connections/CURRENT_CONNECTIONS',
};
